//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3053
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UptimeCheck.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UptimeCheck.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}日{1}時間{2}分{3}秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DateWithDayFormat {
            get {
                return ResourceManager.GetString("DateWithDayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}時間{1}分{2}秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DateWithoutDayFormat {
            get {
                return ResourceManager.GetString("DateWithoutDayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ位置の自動調整機能を有効にしているため、ウィンドウを移動することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MoveCancelHelpText {
            get {
                return ResourceManager.GetString("MoveCancelHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在の不透明度 : {0}% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpacityTextFormat {
            get {
                return ResourceManager.GetString("OpacityTextFormat", resourceCulture);
            }
        }
    }
}
